### PR TITLE
Use oref instead of dedicated slot accessors

### PR DESCRIPTION
**Pull request by tarsius**
See https://github.com/magit/magit/pull/3309.

### CODE REVIEW

**Comment by vermiculus** [comment]
Should we explicitly require eieio here?

**Comment by tarsius** [comment]
There isn't anything that Melpa could update because I haven't actually pushed the Magit change to its `master` branch yet.

**Comment by vermiculus** [comment]
True; just noting that it's nothing to worry about 😄 I'll re-run the check when the time comes.

**Comment by tarsius** [comment]
Who said I was worried :stuck_out_tongue_winking_eye:
More disappointed I will have to bang on `magit-section-match` before I nuke it, as Magit's tests revealed.

**Comment by tarsius** [comment]
I have merged https://github.com/magit/magit/pull/3309, so you should merge this too now.

Here's an unrelated warning I ran into when making sure that my changes didn't produce any:

```
magithub-core.el:1083:20:Warning: magithub-cache called with 1 argument, but
    requires 2+
```

**Pull request merged**
