### PR TITLE
Parse correctly git+ssh remote urls

### PR DESCRIPTION
**Pull request by diasjorge**

### CODE REVIEW

**Comment by vermiculus** [comment]
Looks good; I'm ready to merge. The Travis tests are still failing, but it's not your fault. Would you mind terribly if I kept this PR open to figure out why?

**Comment by diasjorge** [comment]
sure no problem, I think you may need to set this for the build ```git config --global github.user``` from the ghub docs

**Comment by vermiculus** [comment]
That makes sense, but it's odd I've never had to do this in my own remote builds.

**Comment by vermiculus** [comment]
Can you rebase to see if fc29f0ece86c23a3e3561d7b13728fe375c3c535 fixes the authentication stuff?

**Pull request merged**
