### PR TITLE
Add some documentation for two-factor auth

### PR DESCRIPTION
**Pull request by Blaisorblade**
First, thanks for this package!

Figuring out support for two-factor authentication (2FA) wasn't trivial. Since there isn't a wizard where to paste a token and check it's correct, at least add some summarized docs, specialized for magithub—since Ghub's docs can't contain client-specific information.

Notes:

- I don't like this solution, I just like it better than just filing an issue.

- Feel free to move that info to a 2FA subsection, but the link belongs to the intro docs since 2FA shouldn't be an obscure feature, but part of the "recommended" setup.

### Security

I'm also not sure what's adequate security for the token. Ghub's docs only say

> Secrets are stored in ~/.authinfo in plain text. If you don’t want that (good choice), then you have to customize auth-sources, e.g. by flipping the positions of the first two elements.

but I don't have GPG setup at all, let alone setup with Emacs and I don't plan to shave that yak yet — customizing auth-sources can't possibly be enough?

EDITED: So I guess that for users without 2FA tokens do get written in cleartext in `~/.authinfo`? Guess that's unavoidable until support for keystores is automated enough, and a tolerable compromise on "secure enough" client machines.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Build failures https://travis-ci.org/vermiculus/magithub/jobs/345908758#L1070 and https://travis-ci.org/vermiculus/magithub/jobs/345908759#L1080 appear unrelated to my PR (right?), so please don't hold them against it.

**Comment by vermiculus** [comment]
Re Travis builds: yeah, it does that sometimes. It's supremely annoying, but there's an open ticket about it somewhere on debbugs I think.

**Comment by vermiculus** [comment]
Related: magit/ghub#47

**Comment by vermiculus** [comment]
Hard-wrapped and used Org syntax. Thanks!

**Pull request merged**
