### PR TITLE
Make magithub-preferred-remote-method a defcustom

### LINKED ISSUE #180: [Question/feature request] Is there any way to use https for fork remotes?
As the title says, it'd be nice to have an option for what protocol is used for fork remotes.

### PR DESCRIPTION
**Pull request by dieggsy**
Closes #180

### CODE REVIEW

**Comment by vermiculus** [comment]
Looks good from here! I'll have to wait until I get home to test, but you can expect this to be merged tonight.

Thanks!

**Comment by dieggsy** [comment]
Any updates on this? (I've since switched to preferring ssh anyway 😄 but just checking)

**Comment by vermiculus** [comment]
My in-laws will be here in a few minutes, so it's been a pretty frantic cleaning party for the past few days 😄 I haven't forgotten about this.

**Comment by vermiculus** [comment]
Thanks again!

**Pull request merged**
