### PR TITLE
Add magithub-browse-file

### PR DESCRIPTION
**Pull request by manateelazycat**

### CODE REVIEW

**Comment by vermiculus** [comment]
I've done some light code cleanup (break up long lines, etc.) and revised the docstring. I'll merge after I finish testing and plan to push any necessary fixes to this branch.

**Comment by vermiculus** [comment]
Merged, thanks!

**Comment by manateelazycat** [comment]
@vermiculus Thanks so much!

**Comment by stardiviner** [comment]
There is a extension named `github-browse-file`, it also supports `github-browse-file-blame` and `github-browse-commit`. I hope it can be in `magithub` too. WDYT?

**Comment by vermiculus** [comment]
What do those functions do?

**Comment by stardiviner** [comment]
Here is the docstring:
```
(github-browse-commit)
Show the GitHub page for the current commit.
```

```
(github-browse-file-blame &optional FORCE-MASTER)

Show the GitHub blame page for the current file. The URL for the webpage is
added to the kill ring. With a prefix argument, "master" is used
regardless of the current branch.

In Transient Mark mode, if the mark is active, highlight the contents of the
region.
```

**Comment by vermiculus** [comment]
`magihtub-commit-browse` already exists.

I'll look at implementing a `magithub-browse-file-blame`.

**Comment by vermiculus** [comment]
Added in https://github.com/vermiculus/magithub/commit/58b9750ec177e8e3e6474c668edfe17d395aee71.

**Comment by stardiviner** [comment]
@vermiculus I take a test, opened error URL.
When I open blame from GitHub, it is https://github.com/stardiviner/emacs.d/blame/9461bc9408aa995a654cb5270d79916be8426143/init.el
And I use `magithub-browse-file-blame` It is  https://github.com/stardiviner/emacs.d/blame/f92a80c18ddc7faae5ed30c76cad47bd4551607f/init.el#L1-L1

The commit is different and invalid.

**Comment by vermiculus** [comment]
Can you expand on how it is 'invalid'? I don't understand what you're doing or what you expect to happen.

**Comment by stardiviner** [comment]
The second URL is opened by magithub which provide an invalid commit hash in URL. So I open URL, GitHub shows nothing there.

**Comment by vermiculus** [comment]
Ensure that commit has been pushed

**Comment by stardiviner** [comment]
I'm sure that line (with or without region selected) text is pushed already. But seems the commit hash is wrong. I indeed have unpushed content of the file. But it should not work like this.

**Comment by vermiculus** [comment]
please open an issue

**Pull request merged**
