### PR TITLE
Various cosmetics

### PR DESCRIPTION
**Pull request by tarsius**
So I am reading the source and ran into some cosmetic issues... :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by vermiculus** [comment]
Thanks!!

**Comment by vermiculus** [comment]
This was merged as ea29269678a9363a0d88d0a237bf28361c2f6681. I was trying to reword the merge commit and it ended up rebasing instead; I pushed to `master` to just merge anyway, but then realized that github wouldn't realize the commits were the same since the rebase changed all the SHAs.

Is this something I should open a tracking issue for on magit? Seems…weird.

**Comment by tarsius** [comment]
Doesn't sound like Magit is to blame, unless you used its new features that are supposed to make that easier and it somehow didn't work:

* `b y`
* make changes
* `p - f p`
* `m i`

(See release announcement for details. Cases in which it is known that this won't work is when the contributor does not allow the maintainer to push to the pull-request branch or when the pull-request was created from the default branch (usually `master`).)

**Comment by vermiculus** [comment]
I did `r w` on the merge commit (wanted to reference the pull number) and proceeded through the warning; after that it started a rebase. Not sure if that's something I should expect.

**Pull request closed without merging**
