### PR TITLE
Use transient instead of magit-popup in magithub-feature-list

### LINKED ISSUE #402: magithub-feature-autoinject error
Emacs initialization breaks down on
``` emacs-lisp
(after-load 'magit (magithub-feature-autoinject t))
```
with error
```
error: feature pull-request-merge failed to install: nil
```
It seems due to no defination of function "magit-am-popup". Since https://github.com/magit/magit/pull/3728 magit uses Transient instead of Magit-Popup.

### PR DESCRIPTION
**Pull request by mgcyung**
Fix #402

### CODE REVIEW

**Comment by vermiculus** [comment]
Hm, we should probably fix all the transient-related stuff in one go. Would you have time to migrate each popup introduced here? (Search for `magit-define-popup`.)

If not (which is totally fine! I'm grateful for any help you can give me here), if you explicitly `(require 'magit-popup)` in each of the files that call `magit-define-popup` and add it explicitly to the Package-Requires header in `magithub.el`, does the project compile successfully? (Run `make install test`.)

**Comment by mgcyung** [comment]
How to deal with `magit--set-popup-variable` and `magit--format-popup-variable:choices`. There is an error in `make install test`
```
In toplevel form:
magithub-settings.el:383:1:Error: the following functions are not known to be defined: magit--set-popup-variable, magit--format-popup-variable:choices
emake: compiling magithub-settings.el...done
emake: Running target "compile" with function `emake-compile' with arguments ("~error-on-warn")...done
There were compile-time errors
make: *** [emake.mk:74: compile] Error 255
```

**Comment by mgcyung** [comment]
There is an error of no "magit-checkout-pull-request" when run "make
install test". The following code snippet which is irrelevant to
transient is also commented
``` emacs-lisp
;; (make-obsolete 'magithub-pull-request-checkout 'magit-checkout-pull-request "0.1.6")
;; (defalias 'magithub-pull-request-checkout #'magit-checkout-pull-request)
```

**Comment by vermiculus** [comment]
Great! I'll give this a quick run through tonight and give some feedback / merge as appropriate.

Thanks for taking this on!

**Comment by hexmode** [comment]
Please merge this PR.  It works for me!

**Comment by vermiculus** [comment]
@hexmode I'm trusting you, here 😄 

I've not had the bandwidth or frankly the energy for F/OSS work lately – I've been dealing with some safety-critical systems at work and they've been consuming all my efforts.

I'm merging this PR now. If it stops working, please let me know and I'll rewind ASAP.

**Comment by hexmode** [comment]
Thank you! testing now.

**Pull request merged**
