### PR TITLE
correct spelling mistake

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by vermiculus** [comment]
thanks!

**Comment by vermiculus** [comment]
By the way, it seems like you do this a lot -- out of curiosity, how?

**Comment by EdwardBetts** [comment]
With codespell: https://github.com/lucasdemarchi/codespell

**Comment by vermiculus** [comment]
Of course, but surely you must also have some sort of search/fork/PR script to go along with it.

**Comment by EdwardBetts** [comment]
You're right. I wrote something with PyGithub and GitPython.

**Comment by vermiculus** [comment]
Neat, I'll have to check them out. Thanks for the info!

**Pull request merged**
