### PR TITLE
Add docs for skipping labels when creating an issue

### LINKED ISSUE #326: Submit issue after selecting tags
The documentation is unclear on how to submit an issue after creating it. Documenting here for other folks that run into this:

- After creating the issue, submit it using the appropriate command (C-c C-c, or M-x magithub-edit-submit with a default Spacemacs configuration).
- This opens the Label selection options. Use arrow keys and `RET` to select any desired labels
- Enter `""` in the label field, then `C-RET` to continue submitting

### PR DESCRIPTION
**Pull request by jeffjewiss**
Closes #326

### CODE REVIEW

**Comment by vermiculus** [comment]
Thanks! Do you think it's worthwhile to add resources about how to do this in the popular completion frameworks? (I only know of Ivy and Helm; are there others?) I think that was the root cause of the original confusion (since you must C-M-j in ivy to accept without input, for example).

**Comment by jeffjewiss** [comment]
Yeah, I think that would be a good addition and having a note about the completion framework (and maybe using ivy as an example) would be helpful.

I'll look at adding that to the PR.

**Comment by jeffjewiss** [comment]
Okay, I've updated this with a brief note as outlined above.

Cheers.

**Comment by vermiculus** [comment]
Thanks!

**Pull request merged**
