### PR TITLE
create non-existing directory before really run process

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by vermiculus** [comment]
Thanks!  I wonder though if we should be waiting to create the directory until after the confirmations after all -- if the user quits out (`C-g`), we don't want an empty directory just hanging about.

I'll think about this some more today.  For now, I'm going to amend your commit to correct the release notes, so be sure to pull down the latest changes from your branch if you want to make further changes :smile:

**Comment by stardiviner** [comment]
Thanks for quick response. You're great programmer!

**Comment by vermiculus** [comment]
Merged, but mostly be accident. In the future, please don't name your fork branches 'master' 😄

**Comment by vermiculus** [comment]
Fixes #281.

**Comment by vermiculus** [comment]
Merged as eb8a794df0db2e7edea1106a87bf03f94ec7e192.

**Comment by stardiviner** [comment]
I see. Thanks.

**Pull request closed without merging**
